---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by intellif.
--- DateTime: 2020/9/11 11:11
---

lucy = {name="h",age=17,height=65}
lucy.age=18
print(lucy.age)
print(lucy)


--arr = {"String",1}
--for i, v in ipairs(arr) do
--    print(i,v)
--end

--local a = "12.12;"
--local b = "15";
--local c = a b;
--print(a..b )

--[[
local function demo1()
    local a = 12;
    local b = 'hehe';
    if a==12 and b=='hehe' then
        print("lua zhenhao xue")
    elseif b == 'hehe' then
        print('这都可以？')
    end
end

demo1();
]]
