server:
  port: 8080
spring:
  application:
    name: crm
  datasource:
#    多数据源配置
    dynamic:
      #设置默认的数据源或者数据源组,默认值即为master
      primary: mysql
      #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      strict: false
      datasource:
        mysql:
          username: "root"
          url: jdbc:mysql://192.168.70.206:3306/crm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          password: "Intellif@2014"
          driver-class-name: com.mysql.cj.jdbc.Driver
        sqlserver:
          url: jdbc:sqlserver://192.168.66.81:1433;DatabaseName=YTLF20190513001
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          username: "kf"
          password: "Introcks@2018"

  redis:
    database: 0
    host: 192.168.70.206
    port: 6379
    flush-mode: on_save

mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  #  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.intellif.crm.common.bean.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    # 热加载mapper文件
    refresh: true
    db-config:
      db-type: sql_server
# mybatis 开启驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.intellif.crm.mapper: debug

# 邮箱配置
email:
  account: liu.yangzhen@intellif.com
  password:
  host: smtp.exmail.qq.com
  port: 465
  protocol: smtp
  recipientAccount: 1174093912@qq.com,183090792@qq.com
#user:
#  ids: '644134832179253530,644134832179253506'

feign:
  client:
    config:
      default:
        connectTimeout: 10000

ribbon:
  ConnectTimeout: 10000 # 连接超时时长
  ReadTimeout: 20000 # 数据通信超时时长
  MaxAutoRetries: 0 # 当前服务器的重试次数
  MaxAutoRetriesNextServer: 0 # 重试多少次服务
  OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试
